web/miapp/urls.py
from django.urls import path, include
from miapp.views import Home, registro
from django.contrib.auth import views as auth_views
from miapp import views


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('registro/', registro, name='registro'),
    path('pagina/', views.pagina, name='pagina'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('miapp.urls','miapp'), namespace='miapp')),
]

web/miapp/models.py
from django.db import models

# Create your models here.

web/miapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class CustomCreationForm(UserCreationForm):
    pass

web/miapp/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin 
from .forms import CustomCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login

from django.contrib.auth.decorators import login_required

# Create your views here.

class Home(LoginRequiredMixin,generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'miapp:login'


def registro(request):
    data = {
        'form': CustomCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            #redirigir al home
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "te has registrado correctamente")
            return redirect(to="/pagina")
        data["form"] = formulario

    return render(request, 'bases/registro.html', data)

@login_required(login_url='miapp:login')
def pagina(request):

    return render(request, 'bases/pagina.html')

web/miapp/templates/bases/home.html
{% extends 'base/base.html' %}
{% load static %}



{% block content %}
<!--<img class="img-fluid" width="1900px" height="30%" src="{% static 'base/img/mona2.jpg' %} "/>-->
<img class="img-fluid" width="1950px" height="30%" src="{% static 'base/img/pcwea.jpg' %} "/>


{% endblock %}

web/miapp/templates/bases/login.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block wea %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}


{% block login %}
<div class="container" >
    
    <!-- Outer Row -->
    <div class="row justify-content-center" >

        <div class="col-xl-12 col-lg-12 col-md-9" >

            <div class="card o-hidden border-0 shadow-lg my-5" >
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        
                        <div class="col-lg-6 d-none d-lg-block " >
                            <img class="img-fluid" width="1950px" height="30%" src="{% static 'base/img/pcwea.jpg' %}"/>
                            
                        </div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Bienvenido!</h1>
                                    <hr>
                                    <br>
                                    
                                </div>
                                <small class="text-danger">
                                    {% if form.errors %}
                                    {% for field in form %}
                                    {% if field.errors %}
                                    {% for error in field.errors %}
                                    {{ error|escape }}
                                    {% endfor %}
                                    {% endif %}
                                    {% endfor %}

                                    {% if form.non_field_errors%}
                                    {% for error in form.non_field_errors %}
                                    {{ error|escape }}
                                    {% endfor %}
                                    {% endif %}
                                    {% endif %}
                                </small>
                                <form class="user" method="POST">
                                    {% csrf_token %}
                                    <!--
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    -->
                                    {{ form.as_p  }}

                                    <br>


                                    <button type="submit" class="btn btn-warning btn-user btn-block">Acceder</button>

                                    <a href="/registro" class="col-xl-12 link-dark">No tienes cuenta? Registrate aqui</a>


                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

web/miapp/templates/bases/pagina.html
{% extends 'base/base.html' %}
{% load static %}



{% block content %}
<img class="img-fluid" width="1950px" height="30%" src="{% static 'base/img/mona3.jpg' %} "/>
<!--<img class="img-fluid" width="1950px" height="30%" src="{% static 'base/img/pcwea.jpg' %} "/>-->


{% endblock %}

web/miapp/templates/bases/registro.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block wea %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}


{% block login %}
<div class="container" >
    
    <!-- Outer Row -->
    <div class="row justify-content-center" >

        <div class="col-xl-12 col-lg-12 col-md-9" >

            <div class="card o-hidden border-0 shadow-lg my-5" >
                
                    <!-- Nested Row within Card Body -->
                    
                        
                        
                        <div class="col-lg-12">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Registro de Usuarios</h1>
                                    <hr>
                                    <br>
                                    
                                </div>
                                
                                <form class="user" method="POST">
                                    {% csrf_token %}
                                    <!--
                                    <div class="form-group">
                                        <input type="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    -->
                                    {{ form.as_p  }}
                                    

                                    <br>


                                    <button type="submit" class="btn btn-warning btn-user btn-block">Registrar</button>
                                    <a href="/login" class="col-xl-12 link-dark">Volver al login</a>


                            </div>
                        </div>
                    
                
            </div>

        </div>

    </div>

</div>
{% endblock %}

web/templates/base/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Web Certificada</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body>
  {% block wea %}
  <nav class="navbar navbar-expand navbar-light bg-dark topbar  static-top shadow">

    <a class="navbar-brand" href="#">
      <img src="{% static 'base/img/django2.png' %}" width="50" height="50" alt="">
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/pagina">Pagina</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contacto</a>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>
        
        <li class="nav-item  dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            @ {{user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Perfil</a>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              Salir
            </a>
          </div>
        </li>
        
      </ul>
    </div>
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>



    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search"
          aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-dark" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>
  </nav>
  {% endblock %}

  {% block content %}
  {% endblock %}

  


  <!-- Footer -->
  {% block footer %}
  <footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>

        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>

        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>

        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      Copyright &copy;
      <script>document.write(new Date().getFullYear());</script>
      Pagina certificada por AWS | DIseno realizado con Django y Boostrap 5
      
    </div>
    <!-- Copyright -->
  </footer>
  {% endblock %}
  <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  {% block login %} {% endblock %}
  
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cerrando Sesion</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body"> Estas seguro de salir??</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="{% url 'miapp:logout' %}">Salir</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

  {% block js_page %}{% endblock %}
</body>

</html>